### PR TITLE
Beneficial str buffs on rez effected targets…

### PR DESCRIPTION
**Pull request by jcon321**
this bug http://www.takproject.net/forums/index.php?threads/during-rez-effects-strength-buff-does-not-hold.4635/

### CODE REVIEW

**Comment by jcon321** [comment]
ah ok that makes sense, I will close this request when I get home later today. i'll make the change and retest and then resubmit the pull request. thanks

**Comment by cavedude00** [comment]
You don't have to close it, you can just update it with the new commit :)

**Comment by jcon321** [comment]
ah ok sweet

**Comment by jcon321** [comment]
ok it works, I tested by rezzing a non admin account. i think tried to cast strength of earth on the target as a druid (from my spell bar) it did not hold. on the non admin account which just got rezzed i casted Yaulp 3 from my spell bar and it landed

**Pull request merged**
