### PR TITLE
fixed bug where HOWLERS (seb/HS portals) would not allow subsequent c…

### PR DESCRIPTION
**Pull request by jcon321**
…lients to click using keyring

trying to use your keyring (not holding the key) on the howlers (seb/HS portal) right after someone else used their keyring to enter would not work... 

this bug http://www.takproject.net/forums/index.php?threads/seb-key-and-keyring.4415/#post-24462

I commented out the part where it says 

close_timer.Start()
SetOpenState(true)

and it worked. so i added logic to check if door name was = to howler than to skip that.

btw I could zone in 2 toons simultaneous into VP with no problem, and that door name is not called HOWLER... so i'm guessing it has something to do with HOWLERS specifically.

if this happens on the sleeper tomb portal (which is not called HOWLER) then maybe we can change these door opentypes to something not being used. but that would require changing more code to fit this new opentype... the other option is to keep adding to this if statement the door_names where these portals fail to work.

### CODE REVIEW

**Comment by cavedude00** [comment]
Really awesome catch figuring this one out. I didn't even think about the possiblity of the portals opening and closing causing this. The issue though is it's best to avoid excluding a single door type if we can. Have you tried simply removing opentype == 58 ? opentype 58 is for portal doors, so I don't see any real reason why they should open and close. Each player needs to click on them to use them, so they should always just remain "closed." Of course, I say this without testing so there could be a very good reason why we want them to open.

Also, we can't change opentype sadly. The client uses that field more than the server does, so we have to send what it is expecting. We could change the field in the db and for how the server uses it, and just send it in the doors packet as 58 but that would be messy.

**Comment by jcon321** [comment]
I thought about removing opentype == 58 but I'm pretty sure objects like the globe in skyfire are opentype 58... so wouldn't that kill the animation of it spinning?

**Comment by jcon321** [comment]
ok the skyfire globe isnt opentype 58 but there 787 doors with opentype 58 while only 378 have destination zones

**Comment by cavedude00** [comment]
I am not seeing any sort of animation packet being sent by this code, so it's likely any animation is handled by the client for us. (That's why it's important to send the opentype the client is looking for.) I can only suggest to give it a try, and see what happens.

**Pull request merged**
